config/routes.rb
#
#  routes.rb
#  Defines the routes for each page in a controller
#

Rails.application.routes.draw do
  
  get 'users/new'

  # Set /home as index/root/home
  root 'static_pages#home'

  # Route a GET request for this URL to the __ action in StaticPagesController
  # Will generate help_path and help_url etc
  
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
#
#  static_pages_controller.rb
#  Defines a controller and its associated actions
#

class StaticPagesController < ApplicationController
  
  # Define actions for this controller
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Define our own helper (basically a function)
  # Return the full title on a per page basis
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Social App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  
  <nav>
    <ul>
      <li><%= link_to "About",    about_path %></li>
      <li><%= link_to "Contact",  contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- This is the main site layout file -->
<html>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <!-- Look for _shim.html.erb, insert results of evaluating into view -->
    <%= render 'layouts/shim' %>
  </head>
  
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
  
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
  A simple social networking application created throughout Michael Hartl's Ruby on Rails Tutorial book. 
  The project uses Ruby on Rails to create a social networking website that models the functionality of Twitter. 
  The book can be downloaded at http://www.railstutorial.org/ .
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Turoial about the social app at the 
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
</p>

app/views/static_pages/home.html.erb
<!-- jumbotron class has special meaning to Bootstrap -->
<div class="center jumbotron">
  <h1>Welcome to the Social App</h1>
  
  <h2>This is the home page for the 
  <a href="http://www.railstutorial.org/"> Ruby on Rails Tutorial</a> 
  sample application.
  </h2>
  
  <!-- Add stub link for signup, use bootstrap predefined button classes -->
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails Logo"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>